### ISSUE TITLE
Tolerations and Node Selector

### ISSUE THREAD

**Issue by sjmiller609** [iplabs/terraform-kubernetes-tiller#4]
If you are interested: https://github.com/astronomer/terraform-kubernetes-astronomer-system-components/commit/e08b962816e3c6ad50269d1e926cc0ad5bfe0170

**Comment by headcr4sh** [comment]
Nice. Would you like to provider a pull request? I'll gladly merge it...

EDIT: Nevermind. Copied the changes over myself. Thanks again! :-)
